version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: openident
      POSTGRES_PASSWORD: openident
      POSTGRES_DATABASE: openident
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
