name: CI

on:
  push:
    branches:
      - dev
      - main

env:
  DEFAULT_PYTHON: 3.8

jobs:
  prepare-base:
    name: Prepare base dependencies
    runs-on: ubuntu-latest
    outputs:
      python-key: ${{ steps.generate-python-key.outputs.key }}
      pre-commit-key: ${{ steps.generate-pre-commit-key.outputs.key }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install base requirements
        id: base
        run: pip install -r requirements.txt
      - name: Install dev requirements
        id: dev
        run: pip install -r requirements_dev.txt

  # lint-flake8:
  #   name: Check flake8
  #   runs-on: ubuntu-latest
  #   needs: prepare-base
  #   steps:
  #     - name: Check out code from GitHub
  #       uses: actions/checkout@v2.3.4
  #     - name: Set up Python ${{ env.DEFAULT_PYTHON }}
  #       uses: actions/setup-python@v2.2.2
  #       id: python
  #       with:
  #         python-version: ${{ env.DEFAULT_PYTHON }}
  #     - name: Restore base Python virtual environment
  #       id: cache-venv
  #       uses: actions/cache@v2.1.6
  #       with:
  #         path: venv
  #         key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
  #           needs.prepare-base.outputs.python-key }}
  #     - name: Fail job if Python cache restore failed
  #       if: steps.cache-venv.outputs.cache-hit != 'true'
  #       run: |
  #         echo "Failed to restore Python virtual environment from cache"
  #         exit 1
  #     - name: Restore pre-commit environment from cache
  #       id: cache-precommit
  #       uses: actions/cache@v2.1.6
  #       with:
  #         path: ${{ env.PRE_COMMIT_CACHE }}
  #         key: ${{ runner.os }}-${{ needs.prepare-base.outputs.pre-commit-key }}
  #     - name: Fail job if pre-commit cache restore failed
  #       if: steps.cache-precommit.outputs.cache-hit != 'true'
  #       run: |
  #         echo "Failed to restore pre-commit environment from cache"
  #         exit 1
  #     - name: Register flake8 problem matcher
  #       run: |
  #         echo "::add-matcher::.github/workflows/matchers/flake8.json"
  #     - name: Run flake8
  #       run: |
  #         . venv/bin/activate
  #         pre-commit run --hook-stage manual flake8 --all-files
